name: deployment
on:
  push:
    branches:
    - main
    - asheshambasta/feature/initial-ideas-and-setup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Build the static site
      run: nix-build -A design-hs-html
    - name: Create the webdir.
      run: mkdir _site 
    - name: Copy nix build results
      run: cp -r result/html/* _site/
    - name: Add CNAME
      run: echo design-hs.smartcoop.xyz > _site/CNAME
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
